### ISSUE TITLE
Merge MyYoastClient into the JS monorepo

### ISSUE THREAD

**Issue by LisanneKluitmans** [Yoast/javascript#3]
## Summary

The my-yoast client package has to be merged into the JavaScript monorepo.

## Explanation

yoast-social-previews, yoastSEO.js, yoast-components, my-yoast client, my-yoast manage and eslint are all merged into the same monorepo to keep all javascript together.

## Technical decisions

All mentioned existing repos above will be placed in their own packages in the monorepo.

**Comment by diedexx** [comment]
We've made some progress on this on the `add-my-yoast-client` branch. This branch can only be used for reference, because the changes have to be re-done.

Here's what we did on the branch and thus what needs to be done again with the most recent MyYoast client code:

1. add `my-yoast-client` to the `javascript/packages` directory, while maintaining the git history.
   1. `cd` to the javascript directory.
   1. Make a branch (on the javascript repo) that contains just the MyYoast (not only client) code and its history. This branch does not need to be pushed to GitHub.
      1. `git fetch https://github.com/yoast/my-yoast master:my-yoast-master`
      1. `git checkout my-yoast-master`.
  1. Make a branch (on the javascript repo) that only contains the MyYoast client code and its history. This branch does not need to be pushed to GitHub.
      1. `git subtree split --prefix=client -b my-yoast-client`.
   1. Branch of the latest javascript `master`.
      1. `git checkout master`.
      1. `git pull`.
      1. `git checkout -b new-add-my-yoast-client`.
   1. Add the `my-yoast-client` branch as a subtree to the packages directory.
      1. `git subtree add --prefix=packages/my-yoast-client my-yoast-client`.
   1. `git push origin new-add-my-yoast-client` (git subtree add commits automatically).
1. Tie down the versions of the dependencies
   1. Some dependencies have a rather flexible version constraint that results in possible versions to be installed that break the existing code. These version constraints need to be updated from "^x.y.z" or "x.*" or "~x.y.z" to "x.y.z", so we know for sure which version we are supporting. ([example](https://github.com/Yoast/javascript/commit/5f75ff1c0176765b53a3da6520ff98237af23c42))
      1. The best way is to check which versions MyYoast installs by itself.
         1. `git clone https://github.com/yoast/my-yoast tmp-my-yoast && cd $_ && cd client`
         1. `yarn install` 
         1. For reach package the MyYoast client depends on with a version constraint that is not specific enough (read: contains `*`, `~` or `^`) check which version was installed.
            1. Find the package.json of the installed depencendy in the `tmp-my-yoast/client/node_modules/REPLACE_WITH_THE_NAME_OF_THE_DEPENCENCY` directory.
      1. Cleanup the tmp MyYoast.
      1. `cd ../../` (cd back to the direcotry the tmp-my-yoast directory is in).
      1. `rm -rf tmp-my-yoast`.
   1. Remove the yarn.lock file in the my-yoast-client.
1. Move code that is shared across the client and manage to the client.
   1. Cherrypick [this commit](https://github.com/Yoast/javascript/commit/2656a1679ce3deef38324944a4850d8ce62c2eaa)
1. Make tests pass
	1. yarn test on MyYoast usually runs in a interactive mode. This fails when using `lerna run test` or `yarn test` in the javascript project root. So, we need to run it "inBound"
	   2. These changes [have already been made once](https://github.com/Yoast/javascript/commit/6317ae9910fbdc9070d9a2fbe2c8f7055a685b60) to the `javascript/package.json` and `javascript/packages/my-yoast-client/scripts/test.js` files on the existing `add-my-yoast-client` branch. Cherrypick those changes.
	1. ... Here's where the made progress stops.

**Comment by omarreiss** [comment]
Let's not do this for now.
