### ISSUE TITLE
Add Dutch adjective exceptions

### ISSUE THREAD

**Issue by FAMarfuaty** [Yoast/javascript#369]
**PRs:**
https://github.com/Yoast/javascript/pull/375
https://github.com/Yoast/YoastSEO.js-premium-configuration/pull/68

We need to add the exception lists of adjectives where in words do not follow regular rules when generating adjectives.

**Comment by agnieszkaszuba** [comment]
CR:
As we discussed, we don't really need the exception checks for adjectives that should have less suffixes added (nor a rule for adjectives ending in -en not getting any suffixes). Getting extra suffixes is not too much of a problem; it is a bigger problem to make exception lists that may not be exhaustive (i.e, to miss the adjectives _should_ in fact get all the suffixes). 

So I recommend for these exception checks to be removed. Also, one exception check still needs to be added: the no consonant doubling exception list (currently named noVowelDoubling; it is good to rename it to noVowelOrConsonantDoubling since it concerns both). This should be added in the addAdjectiveSuffixes file. Also, if it is not too much work, it might be nice to make this list into a nested list that is divided by part of speech (noun, adjective, verb). That way, when adding adjective suffixes, we do not need to go through the whole list but only through the adjectives part.

**Comment by FAMarfuaty** [comment]
As have been discussed, it turns out that we don't need this issue for checking/adding adjective exception. Thus this issue will be closed. For 'no vowel and consonant doubling' exception check will be dealt in new different issue.
