### ISSUE TITLE
Bundle css in @yoast/components

### ISSUE THREAD

**Issue by Xyfi** [Yoast/javascript#517]
PRs: 
https://github.com/Yoast/wordpress-seo/pull/14548
https://github.com/Yoast/javascript/pull/549

Context: For the modal demo app and the admin redesign, team frontend needs a way to bundle the css from the monorepo and use it in the plugin. All css can be bundled in 1 file.

Also see https://github.com/Yoast/javascript/pull/518#issuecomment-596498253

## To do
- [x] Close https://github.com/Yoast/javascript/pull/518
- [x] Create a js file for each of the components for which HTML/CSS has been written.
    - [x] Import the corresponding CSS to those files.
- [x] Implement a CSS loader in the webpack config that bundles all CSS file into 1 CSS file.
  - [x] Use `css-loader` to load css into js files.
  - [x] Use [mini-css-extract](https://webpack.js.org/plugins/mini-css-extract-plugin/#extracting-all-css-in-a-single-file) to extract the css from the js files to one single file
- [x] Use the css file that has been bundled in the plugin.
- [x] Document the changes in the Readme.md of the monorepo.
     - Communicate to MaxServe that this has been changed
     - Communicate in #dev-plugin that this has been changed
- [ ] Ask @igorschoester to do a major release of `@yoast/components` after this PR has been merged (when it's time to de a release. There is no extra release needed).

**Comment by atimmer** [comment]
For context: Alexander asked what the best way is to solve this problem. I will put my current understanding of the problem below.

**Problem**: We want to generate 1 CSS file for the plugin, so that file can be used for pages where there are no React components. We want users of React components to only receive the CSS that is actually required for those React componentas.

**Solution**: At the top of React components we put an `@import "./css/component.css`. Then we add the `css-loader` where the React components are used. This will result in 1 CSS file for the plugin, because the plugin imports the `index.js` and the `index.js` imports all components. And this will also work if you only import 1 component. Only downside is that this is a breaking change for all consumers of the packages. But that is essentially impossible to avoid when making such a breaking change to the CSS tooling. I would say all affected packages do a major release and mention the breaking change in the changelog.
